
server:
  port: 8686
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        default-application-name: ${spring.application.name}
        #配置本地
        #native:
          #search-locations: classpath:/config/
        # 配置git仓库
        git:
          # git仓库地址
          uri: https://github.com/yanming-work/config_demo
          # 配置仓库路径
          search-paths: yml
          label: master
          # 访问git仓库的用户密码 如果Git仓库为公开仓库，可以不填写用户名和密码，如果是私有仓库需要填写
          #username: username
          #password: *********
# 注册中心配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/