#RewritePath GatewayFilter Factory
#
#在Nginx服务启中有一个非常强大的功能就是重写路径，Spring Cloud Gateway默认也提供了这样的功能，这个功能是Zuul没有的。
spring:
  profiles: rewritepath_route
  cloud:
    gateway:
      routes:
        - id: rewritepath_route
          uri: http://httpbin.org:80/get
          filters:
            - RewritePath=/foo/(?<segment>.*), /$\{segment}
          predicates:
            - Path=/foo/**