
spring:
  profiles: cloud_route
  cloud:
    gateway:
      discovery:
        locator:
          #true，表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务。
          enabled: true
          #将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了），比如以/service-hi/*的请求路径被路由转发到服务名为service-hi的服务上。
          lowerCaseServiceId: true
      routes:
        - id: eureka-provider
          uri: lb://EUREKA-PROVIDER
          predicates:
            #将以/demo/**开头的请求都会转发到uri为lb://EUREKA-PROVIDER的地址上，lb://EUREKA-PROVIDER即eureka-provider服务的负载均衡地址，并用StripPrefix的filter 在转发之前将/demo去掉。
            - Path=/demo/**
          filters:
            - StripPrefix=1
            - RequestTime=true

