
spring:
  profiles: after_route
  cloud:
    gateway:
      routes:
      - id: after_route
        uri: http://httpbin.org:80/get
        predicates:
        #+08:00是指时间和UTC时间相差八个小时，时间地区为Asia/Shanghai。
        - After=2019-02-28T10:00:00+08:00[Asia/Shanghai]
        #- After=2019-02-28T18:00-07:00[America/Denver]
