
server:
  port: 7777
spring:
  application:
    name: service-gateway
  profiles:
    active: cloud_route
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug

#可以分多个文件配置，也可以写在一个文件中用“---”换行隔开。

