#限流

spring:
  profiles: limit_route
  cloud:
    gateway:
      routes:
        - id: limit_route
          uri: http://httpbin.org:80/get
          predicates:
            - After=2019-02-28T10:00:00+08:00[Asia/Shanghai]
          filters:
            - name: RequestRateLimiter
              args:
                #用于限流的键的解析器的 Bean 对象的名字。它使用 SpEL 表达式根据#{@beanName}从 Spring 容器中获取 Bean 对象。
                key-resolver: '#{@hostAddrKeyResolver}'
                #令牌桶每秒填充平均速率
                redis-rate-limiter.replenishRate: 1
                #令牌桶总容量
                redis-rate-limiter.burstCapacity: 3
  redis:
    host: 192.168.1.151
    port: 6379
    database: 10
    password: msaredis


