server:
  port: 10000
  spring:
    application:
      name: eureka-server
  eureka:
    instance:
      hostname: peer3
    client:
      serviceUrl:
        defaultZone: http://peer1:10000/eureka/,http://peer2:10000/eureka/,http://peer3:10000/eureka/
