
server:
  port: 8001
spring:
  application:
    name: eureka-client
# 注册中心配置
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:10000/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: true
