server:
  port: 5577

spring:
  application:
    name: service-hystrix-turbine

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"

turbine:
  #多个用逗号隔开
  app-config: service-hystrix-dashboard
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")
  combine-host: true
  instanceUrlSuffix:
    default: actuator/hystrix.stream