server:
  port: 8060
spring:
  application:
    name: eureka-provider
# 注册中心配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:10000/eureka/
      #defaultZone: http://localhost:10000/eureka/
  #instance:
    #instance-id: ${spring.application.name}
    #prefer-ip-address: true
  #server:
    #enable-self-preservation: false

